import "./globals.css";

export const metadata = {
  title: "Problems - Leetcode",
  description: "Generated by create next app",
};

import { Inter } from "next/font/google";
import { Navbar } from "./common";

const inter = Inter({
  weight: ["300", "400", "500", "600", "700", "900"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
